In [1]:
# import dependencies
import pandas as pd
from datetime import datetime

In [2]:
# Merge 2022 and 2023 csv files
bike_df = pd.concat(
    map(pd.read_csv, ['data/202201.csv', 'data/202202.csv', 'data/202203.csv', 'data/202204.csv', 'data/202205.csv', 'data/202206.csv', 'data/202207.csv', 'data/202208.csv', 'data/202209.csv', 'data/202210.csv', 'data/202211.csv', 'data/202212.csv', 'data/202301.csv', 'data/202302.csv', 'data/202303.csv', 'data/202304.csv', 'data/202305.csv', 'data/202306.csv', 'data/202307.csv', 'data/202308.csv', 'data/202309.csv', 'data/202310.csv', 'data/202311.csv', 'data/202312.csv']), ignore_index=True)

# Display dataframe
bike_df.head

<bound method NDFrame.head of                   ride_id  rideable_type           started_at  \
0        CA5837152804D4B5  electric_bike  2022-01-26 18:50:39
1        BA06A5E45B6601D2   classic_bike  2022-01-28 13:14:07
2        7B6827D7B9508D93   classic_bike  2022-01-10 19:55:13
3        6E5864EA6FCEC90D  electric_bike  2022-01-26 07:54:57
4        E24954255BBDE32D  electric_bike  2022-01-13 18:44:46
...                   ...            ...                  ...
1884331  7E862701EE7A6A03   classic_bike  2023-12-20 17:55:41
1884332  DFAF91AB91BE25DB   classic_bike  2023-12-13 14:36:43
1884333  AEE7B49E6EDFAE6F   classic_bike  2023-12-18 16:40:00
1884334  A38E98956AD72EFB   classic_bike  2023-12-02 13:42:51
1884335  F16E0B969D877368   classic_bike  2023-12-19 16:30:13

                    ended_at    start_station_name start_station_id  \
0        2022-01-26 18:51:53  12 St & Sinatra Dr N            HB201
1        2022-01-28 13:20:23      Essex Light Rail            JC038
2        2022-01-10 20:00:37      Essex Light Rail            JC038
3        2022-01-26 07:55:22  12 St & Sinatra Dr N            HB201
4        2022-01-13 18:45:43  12 St & Sinatra Dr N            HB201
...                      ...                   ...              ...
1884331  2023-12-20 18:00:10      Heights Elevator            JC059
1884332  2023-12-13 14:42:31      Heights Elevator            JC059
1884333  2023-12-18 16:45:45       6 St & Grand St            HB302
1884334  2023-12-02 13:50:42       6 St & Grand St            HB302
1884335  2023-12-19 16:36:54       6 St & Grand St            HB302

              end_station_name end_station_id  start_lat  start_lng  \
0         12 St & Sinatra Dr N          HB201  40.750604 -74.024020
1             Essex Light Rail          JC038  40.712774 -74.036486
2             Essex Light Rail          JC038  40.712774 -74.036486
3         12 St & Sinatra Dr N          HB201  40.750604 -74.024020
4         12 St & Sinatra Dr N          HB201  40.750604 -74.024020
...                        ...            ...        ...        ...
1884331  Bloomfield St & 15 St          HB203  40.748720 -74.040487
1884332  Bloomfield St & 15 St          HB203  40.748767 -74.040470
1884333  Bloomfield St & 15 St          HB203  40.744291 -74.034404
1884334  Bloomfield St & 15 St          HB203  40.744398 -74.034501
1884335      Clinton St & 7 St          HB303  40.744398 -74.034501

           end_lat    end_lng member_casual
0        40.750604 -74.024020        member
1        40.712774 -74.036486        member
2        40.712774 -74.036486        member
3        40.750604 -74.024020        member
4        40.750604 -74.024020        member
...            ...        ...           ...
1884331  40.754530 -74.026580        casual
1884332  40.754530 -74.026580        member
1884333  40.754530 -74.026580        member
1884334  40.754530 -74.026580        member
1884335  40.745420 -74.033320        member

[1884336 rows x 13 columns]>

In [3]:
# Rename columns
bike_df = bike_df.rename(columns={'ride_id': 'Ride ID'})
bike_df = bike_df.rename(columns={'rideable_type': 'Rideable Type'})
bike_df = bike_df.rename(columns={'started_at': 'Started At'})
bike_df = bike_df.rename(columns={'ended_at': 'Ended At'})
bike_df = bike_df.rename(columns={'start_station_name': 'Start Station Name'})
bike_df = bike_df.rename(columns={'start_station_id': 'Start Station ID'})
bike_df = bike_df.rename(columns={'end_station_name': 'End Station Name'})
bike_df = bike_df.rename(columns={'end_station_id': 'End Station ID'})
bike_df = bike_df.rename(columns={'start_lat': 'Latitude'})
bike_df = bike_df.rename(columns={'start_lng': 'Longitude'})
bike_df = bike_df.rename(columns={'end_lat': 'End Lat'})
bike_df = bike_df.rename(columns={'end_lng': 'End Lng'})
bike_df = bike_df.rename(columns={'member_casual': 'User Type'})

# Display dataframe
bike_df.head()

,Ride ID,Rideable Type,Started At,Ended At,Start Station Name,Start Station ID,End Station Name,End Station ID,Latitude,Longitude,End Lat,End Lng,User Type
0,CA5837152804D4B5,electric_bike,2022-01-26 18:50:39,2022-01-26 18:51:53,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member
1,BA06A5E45B6601D2,classic_bike,2022-01-28 13:14:07,2022-01-28 13:20:23,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,member
2,7B6827D7B9508D93,classic_bike,2022-01-10 19:55:13,2022-01-10 20:00:37,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,member
3,6E5864EA6FCEC90D,electric_bike,2022-01-26 07:54:57,2022-01-26 07:55:22,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member
4,E24954255BBDE32D,electric_bike,2022-01-13 18:44:46,2022-01-13 18:45:43,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member

In [4]:
# Replace words
bike_df['Rideable Type'] = bike_df['Rideable Type'].replace(
    {'classic_bike': 'Classic Bike', 'electric_bike': 'Electric Bike', 'docked_bike': 'Docked Bike'})
bike_df['User Type'] = bike_df['User Type'].replace(
    {'member': 'Member', 'casual': 'Casual'})

# Display dataframe
bike_df.head()

,Ride ID,Rideable Type,Started At,Ended At,Start Station Name,Start Station ID,End Station Name,End Station ID,Latitude,Longitude,End Lat,End Lng,User Type
0,CA5837152804D4B5,Electric Bike,2022-01-26 18:50:39,2022-01-26 18:51:53,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,Member
1,BA06A5E45B6601D2,Classic Bike,2022-01-28 13:14:07,2022-01-28 13:20:23,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,Member
2,7B6827D7B9508D93,Classic Bike,2022-01-10 19:55:13,2022-01-10 20:00:37,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,Member
3,6E5864EA6FCEC90D,Electric Bike,2022-01-26 07:54:57,2022-01-26 07:55:22,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,Member
4,E24954255BBDE32D,Electric Bike,2022-01-13 18:44:46,2022-01-13 18:45:43,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,Member

In [5]:
# Make starttime and stoptime datetime
bike_df['Started At'] = pd.to_datetime(bike_df['Started At'])
bike_df['Ended At'] = pd.to_datetime(bike_df['Ended At'])

# Display dataframe
bike_df.head()

,Ride ID,Rideable Type,Started At,Ended At,Start Station Name,Start Station ID,End Station Name,End Station ID,Latitude,Longitude,End Lat,End Lng,User Type
0,CA5837152804D4B5,Electric Bike,2022-01-26 18:50:39,2022-01-26 18:51:53,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,Member
1,BA06A5E45B6601D2,Classic Bike,2022-01-28 13:14:07,2022-01-28 13:20:23,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,Member
2,7B6827D7B9508D93,Classic Bike,2022-01-10 19:55:13,2022-01-10 20:00:37,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,Member
3,6E5864EA6FCEC90D,Electric Bike,2022-01-26 07:54:57,2022-01-26 07:55:22,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,Member
4,E24954255BBDE32D,Electric Bike,2022-01-13 18:44:46,2022-01-13 18:45:43,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,Member

In [6]:
# Create start_date and start_time columns
bike_df['Start Date'] = pd.to_datetime(bike_df['Started At']).dt.date
bike_df['Start Time'] = pd.to_datetime(bike_df['Started At']).dt.time

# Create stop_date and stop_time columns
bike_df['End Date'] = pd.to_datetime(bike_df['Ended At']).dt.date
bike_df['End Time'] = pd.to_datetime(bike_df['Ended At']).dt.time

# Display dataframe
bike_df.head()

,Ride ID,Rideable Type,Started At,Ended At,Start Station Name,Start Station ID,End Station Name,End Station ID,Latitude,Longitude,End Lat,End Lng,User Type,Start Date,Start Time,End Date,End Time
0,CA5837152804D4B5,Electric Bike,2022-01-26 18:50:39,2022-01-26 18:51:53,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,Member,2022-01-26,18:50:39,2022-01-26,18:51:53
1,BA06A5E45B6601D2,Classic Bike,2022-01-28 13:14:07,2022-01-28 13:20:23,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,Member,2022-01-28,13:14:07,2022-01-28,13:20:23
2,7B6827D7B9508D93,Classic Bike,2022-01-10 19:55:13,2022-01-10 20:00:37,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,Member,2022-01-10,19:55:13,2022-01-10,20:00:37
3,6E5864EA6FCEC90D,Electric Bike,2022-01-26 07:54:57,2022-01-26 07:55:22,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,Member,2022-01-26,07:54:57,2022-01-26,07:55:22
4,E24954255BBDE32D,Electric Bike,2022-01-13 18:44:46,2022-01-13 18:45:43,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,Member,2022-01-13,18:44:46,2022-01-13,18:45:43

In [7]:
# Make start_date and stop_date datetime
bike_df['Start Date'] = pd.to_datetime(bike_df['Start Date'])
bike_df['End Date'] = pd.to_datetime(bike_df['End Date'])

In [8]:
# Convert types
bike_df['Ride ID'] = bike_df['Ride ID'].astype(str)
bike_df['Rideable Type'] = bike_df['Rideable Type'].astype(str)
bike_df['Start Station Name'] = bike_df['Start Station Name'].astype(str)
bike_df['Start Station ID'] = bike_df['Start Station ID'].astype(str)
bike_df['End Station Name'] = bike_df['End Station Name'].astype(str)
bike_df['End Station ID'] = bike_df['End Station ID'].astype(str)
bike_df['User Type'] = bike_df['User Type'].astype(str)

In [9]:
# Display dataframe types
bike_df.dtypes

Ride ID                       object
Rideable Type                 object
Started At            datetime64[ns]
Ended At              datetime64[ns]
Start Station Name            object
Start Station ID              object
End Station Name              object
End Station ID                object
Latitude                     float64
Longitude                    float64
End Lat                      float64
End Lng                      float64
User Type                     object
Start Date            datetime64[ns]
Start Time                    object
End Date              datetime64[ns]
End Time                      object
dtype: object

In [10]:
# Drop null values
bike_df = bike_df.dropna()

# Display dataframe
bike_df.head

<bound method NDFrame.head of                   Ride ID  Rideable Type          Started At  \
0        CA5837152804D4B5  Electric Bike 2022-01-26 18:50:39
1        BA06A5E45B6601D2   Classic Bike 2022-01-28 13:14:07
2        7B6827D7B9508D93   Classic Bike 2022-01-10 19:55:13
3        6E5864EA6FCEC90D  Electric Bike 2022-01-26 07:54:57
4        E24954255BBDE32D  Electric Bike 2022-01-13 18:44:46
...                   ...            ...                 ...
1884331  7E862701EE7A6A03   Classic Bike 2023-12-20 17:55:41
1884332  DFAF91AB91BE25DB   Classic Bike 2023-12-13 14:36:43
1884333  AEE7B49E6EDFAE6F   Classic Bike 2023-12-18 16:40:00
1884334  A38E98956AD72EFB   Classic Bike 2023-12-02 13:42:51
1884335  F16E0B969D877368   Classic Bike 2023-12-19 16:30:13

                   Ended At    Start Station Name Start Station ID  \
0       2022-01-26 18:51:53  12 St & Sinatra Dr N            HB201
1       2022-01-28 13:20:23      Essex Light Rail            JC038
2       2022-01-10 20:00:37      Essex Light Rail            JC038
3       2022-01-26 07:55:22  12 St & Sinatra Dr N            HB201
4       2022-01-13 18:45:43  12 St & Sinatra Dr N            HB201
...                     ...                   ...              ...
1884331 2023-12-20 18:00:10      Heights Elevator            JC059
1884332 2023-12-13 14:42:31      Heights Elevator            JC059
1884333 2023-12-18 16:45:45       6 St & Grand St            HB302
1884334 2023-12-02 13:50:42       6 St & Grand St            HB302
1884335 2023-12-19 16:36:54       6 St & Grand St            HB302

              End Station Name End Station ID   Latitude  Longitude  \
0         12 St & Sinatra Dr N          HB201  40.750604 -74.024020
1             Essex Light Rail          JC038  40.712774 -74.036486
2             Essex Light Rail          JC038  40.712774 -74.036486
3         12 St & Sinatra Dr N          HB201  40.750604 -74.024020
4         12 St & Sinatra Dr N          HB201  40.750604 -74.024020
...                        ...            ...        ...        ...
1884331  Bloomfield St & 15 St          HB203  40.748720 -74.040487
1884332  Bloomfield St & 15 St          HB203  40.748767 -74.040470
1884333  Bloomfield St & 15 St          HB203  40.744291 -74.034404
1884334  Bloomfield St & 15 St          HB203  40.744398 -74.034501
1884335      Clinton St & 7 St          HB303  40.744398 -74.034501

           End Lat    End Lng User Type Start Date Start Time   End Date  \
0        40.750604 -74.024020    Member 2022-01-26   18:50:39 2022-01-26
1        40.712774 -74.036486    Member 2022-01-28   13:14:07 2022-01-28
2        40.712774 -74.036486    Member 2022-01-10   19:55:13 2022-01-10
3        40.750604 -74.024020    Member 2022-01-26   07:54:57 2022-01-26
4        40.750604 -74.024020    Member 2022-01-13   18:44:46 2022-01-13
...            ...        ...       ...        ...        ...        ...
1884331  40.754530 -74.026580    Casual 2023-12-20   17:55:41 2023-12-20
1884332  40.754530 -74.026580    Member 2023-12-13   14:36:43 2023-12-13
1884333  40.754530 -74.026580    Member 2023-12-18   16:40:00 2023-12-18
1884334  40.754530 -74.026580    Member 2023-12-02   13:42:51 2023-12-02
1884335  40.745420 -74.033320    Member 2023-12-19   16:30:13 2023-12-19

         End Time
0        18:51:53
1        13:20:23
2        20:00:37
3        07:55:22
4        18:45:43
...           ...
1884331  18:00:10
1884332  14:42:31
1884333  16:45:45
1884334  13:50:42
1884335  16:36:54

[1881412 rows x 17 columns]>

In [12]:
# Save dataframe to csv
bike_df.to_csv('../module18/citibike.csv', index=False)